apiVersion: v1
kind: Service
metadata:
  name: {{ include "core-payment-solution.fullname" . }}-collector
  labels:
    {{- include "core-payment-solution.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
spec:
  type: ClusterIP
  selector:
    {{- include "core-payment-solution.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: collector
  ports:
    - name: ingest
      port: {{ .Values.collector.service.ingestPort }}
      targetPort: ingest
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "core-payment-solution.fullname" . }}-dashboard
  labels:
    {{- include "core-payment-solution.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
    app.kubernetes.io/part-of: dashboard
  {{- with .Values.collector.dashboard.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.collector.dashboard.service.type }}
  selector:
    {{- include "core-payment-solution.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: collector
  ports:
    - name: dashboard
      port: {{ .Values.collector.dashboard.service.port }}
      targetPort: dashboard
      protocol: TCP
