{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "core-payment-solution.fullname" . }}
  labels:
    {{- include "core-payment-solution.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "core-payment-solution.slackSecretKey" . }}: {{ .Values.notifications.slack.webhookUrl | quote }}
  {{ include "core-payment-solution.dashboardSecretKey" . }}: {{ required "secrets.dashboardToken is required when not using secrets.existingSecret" .Values.secrets.dashboardToken | quote }}
{{- end }}
